### ISSUE TITLE
Networking details

### ISSUE THREAD

**Issue by oletos7j** [NetAppDocs/cloud-tiering#20]
Page: [Cloud Tiering technical FAQ](https://docs.netapp.com/us-en/cloud-tiering/faq.html)

> **What are the networking requirements?**
You need a connection between your ONTAP cluster and the object storage provider. The NetApp Service Connector needs an outbound connection to your ONTAP clusters, to the object store, and to the Cloud Tiering service.

"A connection" is very generic and does not specify the type of transmission needed. Is this TCP or UDP, what port number or port range? I would like to request for more detailed information.

**Comment by netapp-bcammett** [comment]
Thank you for your feedback. I'm verifying the details with our technical experts and will get back to you as soon as I hear.

**Comment by netapp-bcammett** [comment]
To follow up, all connections are over port 443 (HTTPS). We'll be updating the documentation to include this information.

**Comment by netapp-bcammett** [comment]
The documentation has been updated. Thanks again for your feedback!
